app/modules/account/models.py
from app import db


class User(db.Document):
    """
    User model
    """
    username = db.StringField(required=True, unique=True, max_length=80)
    email = db.EmailField(required=True, unique=True)
    password = db.StringField()
    first_name = db.StringField(max_length=120)
    last_name = db.StringField(max_length=120)
    created = db.DateTimeField()
    updated = db.DateTimeField()

    meta = {
        'ordering': ['-created'],
        'collection': 'users'
    }

app/modules/news/models.py
from app import db


class Category(db.Document):
    """
    Category model
    """
    title = db.StringField(required=True, unique=True, max_length=120)
    order = db.IntField(default=0)
    created = db.DateTimeField()
    updated = db.DateTimeField()

    meta = {
        'order': ['order'],
        'collection': 'categories'
    }


class NewsItem(db.Document):
    """
    News item model
    """
    title = db.StringField(required=True, unique=True, max_length=120)
    category = db.ReferenceField(Category)
    content = db.StringField(required=True)
    published = db.BooleanField(default=False)
    created = db.DateTimeField()
    updated = db.DateTimeField()

    meta = {
        'ordering': ['-created'],
        'collection': 'news'
    }

app/modules/admin/forms.py
from flask_wtf import Form
from wtforms import StringField


class CategoryForm(Form):
    """
    Form for create/update category
    """
    title = StringField()

app/__init__.py
from flask import Flask, make_response
from flask.ext.restful import Api
from flask.ext.mongoengine import MongoEngine

app = Flask(__name__)
app.config.from_object('settings')
db = MongoEngine(app)
api = Api(app, prefix='/api/v1')


@api.representation('application/json')
def json_representation(data, code, *args, **kwargs):
    resp = make_response(data, code)
    return resp


def register_blueprints():
    from app.modules.core import core
    from app.modules.account import account
    from app.modules.news import news
    from app.modules.admin import admin

    app.register_blueprint(core, url_prefix='/')
    app.register_blueprint(account, url_prefix='/account')
    app.register_blueprint(news, url_prefix='/news')
    app.register_blueprint(admin, url_prefix='/admin')

register_blueprints()

app/modules/account/__init__.py
from flask import Blueprint

account = Blueprint('account', __name__)

from .views import *

app/modules/account/views.py
from flask import request
from flask.ext.restful import Resource

from app import api

from . import account
from .models import User


class UsersListResource(Resource):

    def get(self):
        users = User.objects
        return users.to_json()

    def post(self):
        user = User.from_json(request.data)
        user.save()
        return user.to_json(), 204


class UserResource(Resource):

    def get(self, user_id):
        user = User.objects.get(id=user_id)
        return user.to_json()

    def delete(self, user_id):
        return '', 204


api.add_resource(UsersListResource, '/users/')
api.add_resource(UserResource, '/users/<string:user_id>')

app/modules/admin/__init__.py
from flask import Blueprint

admin = Blueprint('admin', __name__)

from views import *

app/modules/admin/contrib/views.py
from exceptions import NotImplementedError

from flask import render_template, request
from flask.views import View


class TemplateView(View):
    """
    Simple template view
    """
    def get_template_name(self):
        """
        Needs implement this method
        """
        raise NotImplementedError()

    def get_context(self):
        """
        Needs implement this method
        """
        raise NotImplementedError()

    def dispatch_request(self, *args, **kwargs):
        print self.get_template_name()
        context = self.get_context()
        return render_template(self.get_template_name(), **context)


class ListView(TemplateView):
    """
    display list of model items
    """
    template_name = None
    model = None

    def get_queryset(self):
        """
        Returns queryset
        """
        return self.model.objects

    def get_template_name(self):
        return self.template_name

    def get_context(self):
        return {
            'queryset': self.get_queryset()
        }


class FormView(TemplateView):
    """"
    Form view for create and update
    """
    template_name = None
    form_class = None
    model = None

    def get_form(self):
        return self.form()

    def get_object(self, id):
        return self.model.find(id)

    def get_template_name(self):
        return self.template_name

    def get_context(self):
        """
        Generate form context
        """
        id = request.params['id']
        obj = self.get_object(id)
        form = self.get_form()
        payload = {
            'form': form
        }

        if obj is not None:
            form.populate_obj(obj)
        return payload

app/modules/admin/views.py
from app.modules.news.models import Category, NewsItem
from contrib.views import (
    ListView,
    FormView
)

from . import admin


class CategoriesListView(ListView):
    model = Category
    template_name = 'admin/categories.html'


class NewsListView(ListView):
    model = NewsItem
    template_name = 'admin/news.html'


class CategoryCreateView(FormView):
    pass


admin.add_url_rule(
    '/categories',
    view_func=CategoriesListView.as_view('categories')
)

admin.add_url_rule(
    '/news',
    view_func=NewsListView.as_view('news')
)

admin.add_url_rule(
    '/categories/new',
    view_func=CategoryCreateView.as_view('new_category'))

app/modules/core/__init__.py
from flask import Blueprint

core = Blueprint('core', __name__)

from .views import *

app/modules/core/views.py
from flask import render_template
from . import core


@core.route('/')
def index():
    return render_template('index.html')

app/modules/news/__init__.py
from flask import Blueprint

news = Blueprint('news', __name__)

from .views import *

app/modules/news/views.py
from flask.ext.restful import Resource

from app import api
from .models import NewsItem, Category


class CategoriesListResource(Resource):

    def get(self):
        categories = Category.objects
        return categories.to_json()


class NewsListResource(Resource):

    def get(self):
        news = NewsItem.objects
        return news.to_json()

    def post(self):
        return {}


class NewsItemResource(Resource):

    def get(self, item_id):
        return {}

    def delete(self):
        return {}, 204

api.add_resource(NewsListResource, '/news/')
api.add_resource(NewsItemResource, '/news/<item_id>/')

api.add_resource(CategoriesListResource, '/categories/')

app/templates/index.html
<!doctype html>
<html class="no-js" lang="en" ng-app="Ualbum">
	<head>
		<title>UAlbum</title>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<link href="/static/bower_components/foundation/css/normalize.css" rel="stylesheet" />
		<link href="/static/bower_components/foundation/css/foundation.css" rel="stylesheet" />
		<link href="/static/css/base.css" rel="stylesheet" />
	</head>
	<body>
	  <header>
			<div class="row">
                <h2><a href="{{ url_for('core.index') }}">UAlbum</a></h2>
				<div class="naw">
					<nav>
						<li class="nav-item"><a href="#/news/">Новини</a></li>
						<li><a href="#/musicians/">Виконавці</a></li>
						<li><a href="#/albums/">Альбоми</a></li>
						<li><a href="#/contacts/">Контакти</a></li>
					</nav>
				</div>
			</div>
		</header>
		<div id="content">
			<div ng-view></div>
		</div>
		<footer class="row">
			<div class="row">&copy @ilavriv</div>
		</footer>
		<script type="text/javascript" src="/static/bower_components/angular/angular.js"></script>
		<script type="text/javascript" src="/static/bower_components/angular-route/angular-route.js"></script>
		<script type="text/javascript" src="/static/bower_components/angular-resource/angular-resource.js"></script>

		<script type="text/javascript" src="/static/js/constants.js"></script>
		<script type="text/javascript" src="/static/js/resources.js"></script>
		<script type="text/javascript" src="/static/js/utils.js"></script>
		<script type="text/javascript" src="/static/js/controllers.js"></script>
		<script type="text/javascript" src="/static/js/app.js"></script>
	</body>
</html>

app/templates/layouts/admin.html
<!doctype html>
<html>
    <head>
        <title>Admin | {% block title %}{% endblock title %}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
		<link href="/static/bower_components/foundation/css/normalize.css" rel="stylesheet" />
		<link href="/static/bower_components/foundation/css/foundation.css" rel="stylesheet" />
        <link href="/static/css/base.css" rel="stylesheet" />
    </head>
    <body>
    <header>
      <div class="row">
          <h2><a href="/admin/">UAlbum admin</a></h2>
          <div class="naw">
		  <nav>
            <li class="nav-item"><a href="{{ url_for('admin.news') }}">Новини</a></li>
            <li><a href="{{ url_for('admin.categories') }}">Категорії</a></li>
	      </nav>
	    </div>
      </div>
    </header>
    <div class="row">
      <div class="container">
        {% block content %}{% endblock content %}
      </div>
    </div>
    </body>
</html>